services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    volumes:
      - .:/app  # Mount the current directory into /app in the container
    image: 533267362844.dkr.ecr.us-east-1.amazonaws.com/walk-eaze/backend:1.0.0
    command:
      [
        "python",
        "-m",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    restart: always
    env_file:
      - ${ENV_FILE}