services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 533267362844.dkr.ecr.us-east-1.amazonaws.com/walk-eaze-backend:1.1.1
    ports:
      - "80:8000"
    volumes:
      - .:/app  # Mount the current directory into /app in the container  
    command:
      [
        "python",
        "-m",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    restart: unless-stopped
    env_file:
      - .env.production